### ISSUE TITLE
Make it easier to view stunnel errors

### ISSUE THREAD

**Issue by edmorley** [memcachier/memcachier-tls-buildpack#12]
In #10 I had to manually edit `memcachier-stunnel.conf` in a one-off dyno to add `output` and `debug` lines, to see what was failing. eg using:
```bash
sed -i '1s;^;output = /app/stunnel.log\ndebug = 6\n;' /tmp/memcachier-stunnel.conf
stunnel /tmp/memcachier-stunnel.conf
```

Ideally there would be an easier way to view any errors - ideas in order of preference:
- Have them appear in the standard Heroku app output (I don't know if there's any way for a background service to do this, which may mean this requires #11)
- Have environment variables that can be set, which enable logging to a file (always logging to a file would probably result in too large of a file)
- Or failing that, add documentation for the manual steps that need to be performed

It may just end up that #11 is the best way forwards, so this isn't needed as a separate ticket.

**Comment by dterei** [comment]
I think #11 is the best way forward here, but let's leave this open to track.
