### ISSUE TITLE
Add support for Heroku-16 stack

### ISSUE THREAD

**Issue by edmorley** [memcachier/memcachier-tls-buildpack#13]
Heroku's Ubuntu 16.04 based stack is now out of beta:
https://blog.heroku.com/heroku-16-is-generally-available

To add support for this new stack, either:
1. A new version of upstream stunnel needs to be built and uploaded to memcachier's S3 bucket, and `bin/compile` adjusted. The latest upstream stunnel is 5.41 (https://www.stunnel.org/sdf_ChangeLog.html).
2. The buildpack could use heroku-16's native stunnel binary (a la #6), since it ships with openssl 1.0.2g-1​ubuntu4.6 and stunnel 5.30, so isn't affected by #7.

If option 2 is preferred, I'd be able to work on a PR, though for option 1 someone from memcachier would need to work on it.

Thoughts? :-)

**Comment by dterei** [comment]
I think (2) sounds like a good idea. We'd really appreciate any work you're willing to put in on it.

**Comment by edmorley** [comment]
Great! I'll open a PR for this shortly, since this is the last blocker for moving our project's apps to Heroku-16.

I agree (2) is preferred - and in fact I was wondering if we should stop vendoring for cedar-14 too, given that (a) #7 is still some time away, (b) heroku-buildpack-redis has stopped vendoring too (#11 is likely going to be borrowing parts of that buildpack... not that it means we can't still vendor here, but the fewer the differences the easier it will be to keep in sync with them in the future).
