### ISSUE TITLE
localhost:11211 failed

### ISSUE THREAD

**Issue by bmedenwald** [memcachier/memcachier-tls-buildpack#18]
After resetting my stats yesterday, I'm seeing 0% usage of my production MemCachier. This jives with my database usage and logs. Here's what my logs are showing:

```
2018-11-15T16:28:36.630562+00:00 app[web.1]: Dalli/SASL authenticating as 4BE2A0
2018-11-15T16:28:36.636724+00:00 app[web.1]: localhost:11211 failed (count: 1) Errno::ECONNRESET: Connection reset by peer
2018-11-15T16:28:36.636835+00:00 app[web.1]: localhost:11211 is down
```

Looking at #16, it occurs to me that the certificates might be dead yet again. When I followed those instructions with my URL, it shows no certificate at all. Note my port is different (11211 vs the other's example of port 11219). If I run the same command as the other user with his port number instead of mine, I receive the same expired certificate that he saw.

Is this just broken?

**Comment by saschat** [comment]
I am looking into it.

**Comment by saschat** [comment]
This is fixed now. Sorry it took so long. We switched to letsencrypt with automatic renewal for all our other certificates but these slipped through. We will make sure to automate these too. Thanks for bringing this to our attention!

**Comment by saschat** [comment]
Closing this. Leaving #16 open until automated.
