### ISSUE TITLE
Use cedar/cedar-14's bundled stunnel binary

### ISSUE THREAD

**Issue by edmorley** [memcachier/memcachier-tls-buildpack#6]
As of heroku/stack-images#17 stunnel is available natively in the stack image, so we can probably skip the download of the stunnel binary currently performed in `bin/compile`.

**Comment by dreid** [comment]
This doesn't seem like a great idea, considering how old the cedar stunnel is (see https://github.com/memcachier/memcachier-tls-buildpack/issues/7)

**Comment by edmorley** [comment]
Ah true!

**Comment by dterei** [comment]
Closing due to version issue.
