### ISSUE TITLE
Buildpack interferes with key hashing/distribution when using multiple servers

### ISSUE THREAD

**Issue by edmorley** [memcachier/memcachier-tls-buildpack#8]
When making a request, memcache clients will use one of several hashing and distribution methods to determine which of the memcached nodes to connect to. See:
http://sendapatch.se/projects/pylibmc/behaviors.html#hashing

For example the mappings might end up as:
- key with name `foo` -> `server1:11211`
- key with name `bar` -> `server2:11211`

The important point to note is that the client must know which server is expected to contain the value, so as to avoid saving it in multiple places unnecessarily (aside from when a node fails if not using a consistent hashing algorithm), as well as avoid trying to retrieve it from the wrong node, thereby mistakenly seeing a cache miss.

Currently this buildpack makes stunnel listen only on `localhost:11211`, which then round-robins to each node from `MEMCACHIER_SERVERS` (as noted in #2).

Users then set eg `MY_MEMCACHE_SERVERS` to either `localhost:11211` or `localhost:11211,localhost:11211`.

However neither form helps, since they result in:
- key with name `foo` -> `localhost:11211` -> (random_round_robin_choice)
- key with name `bar` -> `localhost:11211` -> (random_round_robin_choice)

This means that request will end up being effectively made to a random memcached node, thereby meaning higher rates of cache misses, plus all keys being stored on all nodes, rather than only on some.

Instead, a separate service should be declared for each node, with some way of differentiating between them (eg by varying localhost port or unix socket). For example:

```
[memcachier1]
connect = FOO.heroku.prod.memcachier.com:11211
accept = localhost:11211

[memcachier2]
connect = BAR.heroku.prod.memcachier.com:11211
accept = localhost:11212
```

The user would then set `MY_MEMCACHE_SERVERS` to `localhost:11211,localhost:11212` (note the different port), which would give eg:
- key with name `foo` -> `localhost:11211` -> `FOO.heroku.prod.memcachier.com:11211`
- key with name `bar` -> `localhost:11212` -> `BAR.heroku.prod.memcachier.com:11211`

I'll open a PR for this shortly.

**Comment by alevy** [comment]
In practice, this doesn't matter for MemCachier and was done intentionally. Behind the scenes, all MemCachier proxies for a particular client use the same backend storage cluster and does it's own, consistent rehashing. Round robin is really the method we'd prefer clients to use (since it would mean load would be distributed amongst proxies regardless of data skew), but for compatibility with other memcache servers, don't enforce that.

**Comment by edmorley** [comment]
Ah I didn't realise it was that custom of a implementation on the backend.
Great - sounds like this isn't needed then :-)

Would you mind adding a comment to `bin/compile`, to indicate that the current behavior is intentional?
